/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const User = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const Visitor = IDL.Record({
  'ip' : IDL.Text,
  'visited' : IDL.Record({
    'optInPage' : IDL.Bool,
    'salesPage' : IDL.Bool,
    'bridgePage' : IDL.Bool,
    'presentationPage' : IDL.Bool,
  }),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'setWebhookUrl' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getWebhookUrl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllVisitors' : IDL.Func([], [IDL.Vec(Visitor)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'mentor' : IDL.Text,
          'totalVisitors' : IDL.Nat,
          'totalSales' : IDL.Nat,
          'coupon' : IDL.Text,
          'totalOptIns' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCompletedOptIns' : IDL.Func([], [IDL.Nat], ['query']),
  'getCouponCode' : IDL.Func([], [IDL.Text], ['query']),
  'getMentorInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getRevisiters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSalesPageViews' : IDL.Func([], [IDL.Nat], ['query']),
  'getVisitorPath' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'optInPage' : IDL.Bool,
          'salesPage' : IDL.Bool,
          'bridgePage' : IDL.Bool,
          'presentationPage' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'incrementCompletedOptIns' : IDL.Func([], [IDL.Nat], []),
  'incrementSalesPageViews' : IDL.Func([], [IDL.Nat], []),
  'trackVisitor' : IDL.Func([IDL.Text], [], []),
  'updateVisitor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const User = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  const Visitor = IDL.Record({
    'ip' : IDL.Text,
    'visited' : IDL.Record({
      'optInPage' : IDL.Bool,
      'salesPage' : IDL.Bool,
      'bridgePage' : IDL.Bool,
      'presentationPage' : IDL.Bool,
    }),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'setWebhookUrl' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getWebhookUrl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllVisitors' : IDL.Func([], [IDL.Vec(Visitor)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'mentor' : IDL.Text,
            'totalVisitors' : IDL.Nat,
            'totalSales' : IDL.Nat,
            'coupon' : IDL.Text,
            'totalOptIns' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCompletedOptIns' : IDL.Func([], [IDL.Nat], ['query']),
    'getCouponCode' : IDL.Func([], [IDL.Text], ['query']),
    'getMentorInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getRevisiters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSalesPageViews' : IDL.Func([], [IDL.Nat], ['query']),
    'getVisitorPath' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'optInPage' : IDL.Bool,
            'salesPage' : IDL.Bool,
            'bridgePage' : IDL.Bool,
            'presentationPage' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'incrementCompletedOptIns' : IDL.Func([], [IDL.Nat], []),
    'incrementSalesPageViews' : IDL.Func([], [IDL.Nat], []),
    'trackVisitor' : IDL.Func([IDL.Text], [], []),
    'updateVisitor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
