/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface User { 'name' : string, 'email' : string, 'timestamp' : Time }
export interface Visitor {
  'ip' : string,
  'visited' : {
    'optInPage' : boolean,
    'salesPage' : boolean,
    'bridgePage' : boolean,
    'presentationPage' : boolean,
  },
  'timestamp' : Time,
}
export interface _SERVICE {
  'createUser' : ActorMethod<[string, string], boolean>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllVisitors' : ActorMethod<[], Array<Visitor>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'mentor' : string,
      'totalVisitors' : bigint,
      'totalSales' : bigint,
      'coupon' : string,
      'totalOptIns' : bigint,
    }
  >,
  'getCompletedOptIns' : ActorMethod<[], bigint>,
  'getCouponCode' : ActorMethod<[], string>,
  'getMentorInfo' : ActorMethod<[], string>,
  'getRevisiters' : ActorMethod<[], Array<string>>,
  'getSalesPageViews' : ActorMethod<[], bigint>,
  'getVisitorPath' : ActorMethod<
    [string],
    {
      'optInPage' : boolean,
      'salesPage' : boolean,
      'bridgePage' : boolean,
      'presentationPage' : boolean,
    }
  >,
  'incrementCompletedOptIns' : ActorMethod<[], bigint>,
  'incrementSalesPageViews' : ActorMethod<[], bigint>,
  'trackVisitor' : ActorMethod<[string], undefined>,
  'updateVisitor' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];