/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Visitor {
    ip: string;
    visited: {
        optInPage: boolean;
        salesPage: boolean;
        bridgePage: boolean;
        presentationPage: boolean;
    };
    timestamp: Time;
}
export interface User {
    name: string;
    email: string;
    timestamp: Time;
}
export interface backendInterface {
    createUser(name: string, email: string): Promise<boolean>;
    getAllUsers(): Promise<Array<User>>;
    getAllVisitors(): Promise<Array<Visitor>>;
    getAnalytics(): Promise<{
        mentor: string;
        totalVisitors: bigint;
        totalSales: bigint;
        coupon: string;
        totalOptIns: bigint;
    }>;
    getCompletedOptIns(): Promise<bigint>;
    getCouponCode(): Promise<string>;
    getMentorInfo(): Promise<string>;
    getRevisiters(): Promise<Array<string>>;
    getSalesPageViews(): Promise<bigint>;
    getVisitorPath(ip: string): Promise<{
        optInPage: boolean;
        salesPage: boolean;
        bridgePage: boolean;
        presentationPage: boolean;
    }>;
    incrementCompletedOptIns(): Promise<bigint>;
    incrementSalesPageViews(): Promise<bigint>;
    trackVisitor(ip: string): Promise<void>;
    updateVisitor(ip: string, page: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllVisitors(): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisitors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisitors();
            return result;
        }
    }
    async getAnalytics(): Promise<{
        mentor: string;
        totalVisitors: bigint;
        totalSales: bigint;
        coupon: string;
        totalOptIns: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCompletedOptIns(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedOptIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedOptIns();
            return result;
        }
    }
    async getCouponCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCouponCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCouponCode();
            return result;
        }
    }
    async getMentorInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMentorInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMentorInfo();
            return result;
        }
    }
    async getRevisiters(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisiters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisiters();
            return result;
        }
    }
    async getSalesPageViews(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesPageViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesPageViews();
            return result;
        }
    }
    async getVisitorPath(arg0: string): Promise<{
        optInPage: boolean;
        salesPage: boolean;
        bridgePage: boolean;
        presentationPage: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorPath(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorPath(arg0);
            return result;
        }
    }
    async incrementCompletedOptIns(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementCompletedOptIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementCompletedOptIns();
            return result;
        }
    }
    async incrementSalesPageViews(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementSalesPageViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementSalesPageViews();
            return result;
        }
    }
    async trackVisitor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackVisitor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackVisitor(arg0);
            return result;
        }
    }
    async updateVisitor(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitor(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
